theme: jekyll-theme-cayman
title: "Nilearn Dev Days 2020"
description: |
             Join the Nilearn development community and shape what's next
baseurl: "/dev-days-2020"
github:
    is_project_page: "false"
